### ISSUE TITLE
Solution tips

### ISSUE THREAD

**Issue by RumblingTurtle** [jeFF0Falltrades/Tutorials#1]
Hi, I managed to get the answer but couldn't figure out the input sequence to get the key so I patched one line in the assembly and it worked. However I feel that it was a kind of a cheaty way of solving it. Are you supposed to do something similar or am I still missing something? Not going to go into any specifics in order not spoil the fun for anyone. And the series are awesome btw! Hope to see more content from you.

**Comment by jeFF0Falltrades** [comment]
Hey RumblingTurtle!

The best part about this challenge is there is no cheating! 

The whole point was to see how creative you could be and there are innumerable ways to get the flag - your method shows you understand how to patch the assembly directly to get the answer you needed, which is a perfectly acceptable and clever solution to this crackme. 

There are several other ways to obtain the flag, but no wrong way in this case - Great work and thank you for the kind words!
