### ISSUE TITLE
Creating a Discord server

### ISSUE THREAD

**Issue by Overload2664** [jeFF0Falltrades/Tutorials#2]
Hey jeFF0Falltrades!
Creating a Discord server(or whatever alternative platform) would allow us to communicate with each other, exchange ideas and meet others interested in RE.
What do you think?

**Comment by jeFF0Falltrades** [comment]
Thanks for submitting this idea! 

I’ve toyed with the idea for a while, and I’m still considering it…I may make a poll after the next video is released to gather level of interest. I’m certainly open to hosting one if we get to that point though. 

Thanks for submitting your interest, and on behalf of other viewers too!

I’m going to close this, but obviously more to follow 😁
