### ISSUE TITLE
Sandbox in a Box Challenge Writeup

### ISSUE THREAD

**Issue by garr3ttmjo** [jeFF0Falltrades/Tutorials#4]
Hi jeFF0Falltrades,

I completed your challenge today and wanted to provide my writeup to add to the Wall of Fame under the user garr3ttmj.

Here is the link: https://github.com/garr3ttmjo/Writeups/blob/main/Sandbox%20in%20a%20Box/README.md

Also wanted to say thank you for the time you spent creating your videos and the challenge. This was my first exposure to malware analysis and you provided a great walkthrough in setting up the VMs and your approach to analyzing malware.

**Comment by jeFF0Falltrades** [comment]
And I want to say: Thank you for taking the time to make this 11/10 write-up - Great explanations and walk-through, and congrats on all you have learned!

I always ask those who take the time to go above and beyond like this: Is it okay for me to share your write-up on my socials (YouTube, Mastodon, LinkedIn) as well? I always love sharing these success stories! Truly motivates me to keep making these kinds of courses :smiley:

Well done, and thanks so much for watching - and keep on learning and sharing!

Write-up added in 2b27f6af9d368a8c431fe0ccac469e032a88ea7a !

**Comment by garr3ttmjo** [comment]
Feel free to share on whatever you would like, I look forward to enjoying more of your content!

**Comment by jeFF0Falltrades** [comment]
> Feel free to share on whatever you would like, I look forward to enjoying more of your content!

Thank you so much for the kind words. And please let me know if you have a LinkedIn or other profile you'd like linked to in the shout-out!

**Comment by garr3ttmjo** [comment]
Here is my LinkedIn - https://www.linkedin.com/in/garrett-jones-073649137/
