### ISSUE TITLE
Sandbox in a Box Crackme write-up

### ISSUE THREAD

**Issue by K0enM** [jeFF0Falltrades/Tutorials#5]
Hey jeFF0Falltrades,

First of all, I love your channel. The quality of your content is amazing and unmatched on YouTube. 

I was looking to update my old FLARE VM setup and I found your series super helpful in adding Remnux + INetSim to my setup. I decided to solve your crackme to make sure I was comfortable with my setup and to make sure I had all the necessary tools installed. I want to get more serious about learning RE and Malware Analysis (particularly dynamic analysis) and I feel like I'm ready to start tearing apart some real malware. 

This is the link to my write-up: [https://www.koenmolenaar.nl/write-ups/jeff0falltrades-sandbox-crackme/](https://www.koenmolenaar.nl/write-ups/jeff0falltrades-sandbox-crackme/), it would be great if you would add it to the Wall of Fame.

Thanks again for all the effort you put in for both this challenge and your content in general!

**Comment by jeFF0Falltrades** [comment]
@K0enM : I love this write-up - I think what I love about it most is you took the useful bits from the master0Fnone course to help solve the problem you were facing, and your write-up on how you utilized the tooling from the tutorial, as well as your own intuition and knowledge, is a great testament to your skill (as both a reverser and a writer)!

Well done!

Your write-up has been added in https://github.com/jeFF0Falltrades/Tutorials/commit/456bfb22d9c71fc8b7712c295e9bfadaa92cb6bc.

Thank you so very much for the kind words, and please keep contributing your work to the community!
